project:
  type: website
  output-dir: docs

website:
  title: "Ashlynn Hainey's Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hobbies.qmd
        text: Hobbies

format:
  html:
    theme: vapor
    css: styles.css
    toc: true



